"""
Paths for the product app. Deliberately independent of the repo root's
config.py, which the ML side flips between local/Kaggle paths for
training -- this app always runs locally and must not be exposed to that.
(Named settings.py, not config.py, so it doesn't collide with the root
module of the same name when both end up on sys.path -- see build_assets.py.)
"""

from pathlib import Path

APP_DIR = Path(__file__).resolve().parent
REPO_ROOT = APP_DIR.parent

ASSETS_DIR = APP_DIR / "assets"                 # generated by data_prep/build_assets.py, read by app.py
MANIFEST_PATH = ASSETS_DIR / "manifest.json"

# data_prep only -- app.py never touches these, it only reads ASSETS_DIR.
LOCAL_CACHE_DIR = REPO_ROOT / "data" / "cache"   # cached .npz + manifest.json (shapenet_car_dataset.py)
LOCAL_CKPT_DIR = REPO_ROOT / "checkpoints"       # best.pt / last.pt / norm_stats.npz (train.py)
